name: "fe: build+run"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "fe/**"
jobs:
  fe-build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn install
        working-directory: ./fe
      - name: Build fe
        run: yarn build
        working-directory: ./fe
